apiVersion: v1
kind: Service
metadata:
  labels:
    app: name-service
  name: name-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: name-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: name-service
  name: name-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name-service
  template:
    metadata:
      labels:
        app: name-service
    spec:
      containers:
      - name: name-service
        image: gcr.io/PROJECT_ID/name-service:0.1.0
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-service
  name: hello-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: hello-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-service
  name: hello-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      labels:
        app: hello-service
    spec:
      containers:
      - name: hello-service
        image: gcr.io/PROJECT_ID/hello-service:0.1.0
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: Always
